version: 0.2

phases:
  install:
    commands:
      - echo install dependencies
  pre_build:
    commands:
      - echo sanity check the installed software?
  build:
    commands:
      - python setup.py sdist
  post_build:
    commands:
      - find .
artifacts:
  files:
    - dist/aws_with-*.tar.gz
  discard-paths: yes
